# Generated by Django 3.1.3 on 2022-07-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnFir', models.CharField(max_length=500)),
                ('columnSec', models.TextField()),
                ('columnTime', models.DateTimeField()),
            ],
        ),
    ]
