# Generated by Django 3.1.3 on 2022-07-11 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_testman'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secConn', models.TextField()),
                ('dateTime', models.DateTimeField()),
                ('firConn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.testman')),
            ],
        ),
    ]
