# Generated by Django 4.0.5 on 2022-07-15 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0008_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
